services:
  web:
    build:
      context: .
      dockerfile: .docker/python/Dockerfile
      args:
        PYTHON_VERSION: ${PYTHON_VERSION:-3.10}
    volumes:
      - ./app:/usr/src/app
    expose:
      - "8000"
    depends_on:
      - db

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql

  nginx:
    build:
      context: ./.docker/nginx
    ports:
    - "443:443"
    - "80:80"
    depends_on:
      - web

volumes:
  db_data:
